# Generated by Django 5.1 on 2024-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
    ]
